### ISSUE TITLE
The project's URL leads to a non-existent Heroku app

### ISSUE THREAD

**Issue by arcanemachine** [dwyl/phoenix-liveview-counter-tutorial#160]
The URL associated with this project is https://live-view-counter.herokuapp.com/ but the app does not exist.

# Todo

+ [x] Create new Fly.io Org with debit card attached. 🆕  ⏳ 💳 
+ [x] Prep project with necessary files to deploy 🧑‍💻 
+ [x] Deploy to Fly.io 🚀 
+ [x] Update Screenshot (`GIF`) in `README.md`: 
https://github.com/dwyl/phoenix-liveview-counter-tutorial/blob/473c48e6a7b99279633cc770b01e1c1ce86258b8/README.md?plain=1#L14-L18

**Comment by nelsonic** [comment]
@arcanemachine thanks very much for opening this issue to remind us that Heroku (Salesforce.com) killed their "Free Tier" ... 

New Fly.io Org created: https://fly.io/dashboard/dwyl-phoenix-liveview-counter

**Comment by nelsonic** [comment]
Keeping this here for later:
https://github.com/dwyl/phoenix-liveview-counter-tutorial/blob/8a1f024a026c21c2b92de78e7e2ca0fa6853f0e5/mix.exs

```elixir
      deps: deps(),
      test_coverage: [tool: ExCoveralls],
      preferred_cli_env: [
        c: :test,
        coveralls: :test,
        "coveralls.detail": :test,
        "coveralls.json": :test,
        "coveralls.post": :test,
        "coveralls.html": :test,
        t: :test
      ]
```

```elixir
  defp aliases do
    [
      setup: ["deps.get"],
      "assets.deploy": ["tailwind default --minify", "esbuild default --minify", "phx.digest"],
      t: ["test"],
      c: ["coveralls.html"],
      s: ["phx.server"]
    ]
  end
```

**Comment by nelsonic** [comment]
https://livecount.fly.dev/ 🔗

**Comment by nelsonic** [comment]
![livecount-fly-dev](https://github.com/dwyl/phoenix-liveview-counter-tutorial/assets/194400/e61cf511-d1d8-4236-83b2-f9f45e06e710)

**Comment by nelsonic** [comment]
PR: #167 contains this update. ✅

**Comment by nelsonic** [comment]
@arcanemachine thanks again for taking the time to open this issue. ❤️
